Contains the last exception that occurred after a call to CallMethod.

Contains an exception if there was an error or ReturnErrorResponse was called or null if there was no error.